---
- name: Restart Apache
  ansible.builtin.service:
    name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
    state: restarted
  become: true

- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  become: true

- name: Restart osTicket
  community.docker.docker_compose:
    project_src: /var/lib/osticket
    state: restarted
  become: true
